name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Install Solana
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v1.17.17/install)"
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          solana --version

      - name: Install Anchor
        run: |
          cargo install --git https://github.com/coral-xyz/anchor --tag v0.29.0 anchor-cli --locked

      - name: Create logs directory
        run: mkdir -p logs

      - name: Run Tests
        run: |
          export RUST_LOG=debug
          export RUST_BACKTRACE=1
          ./scripts/test.sh
        continue-on-error: false

      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-logs
          path: logs/
          retention-days: 14